name: root
channels:
- conda-forge
- damianavila82
- anaconda
- defaults
dependencies:
- pydotplus=2.0.2=py36_0
- rise=5.0.0=py36_0
- graphviz=2.38.0=4
- networkx=1.11=py36_0
- numpy=1.12.1=py36_0
- python-graphviz=0.5.2=py36_0
- scikit-image=0.13.0=np112py36_0
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
